# This file was generated by Agent Outbox. DO NOT EDIT.
cask "agent-outbox" do
  version "0.4.8"

  on_macos do
    on_arm do
      sha256 "43f4c3b6c4b710f021cee471e099af1b4fa4c068b1dbacf6e0b2ab30e14a9601"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.4.8/agent-outbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4e6a04b310fd25f50ecdbd85f6d6ddacc70a05d580daa75973bb764e842170cb"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.4.8/agent-outbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "af92bce58ef1a2d63159c29c54b53189f78c51859227056f36c048baff6c7993"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.4.8/agent-outbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b203409ede1d8c24330ab52a97fcd347b3d5d1ff1cc33aef660c883689c82f1"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.4.8/agent-outbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent-outbox"
  desc "Command-line client for agent-prepared work"
  homepage "https://agent-outbox.dev/"

  livecheck do
    skip "Generated for a numbered release."
  end

  binary "agent-outbox"
end
