# This file was generated by Agent Outbox. DO NOT EDIT.
cask "agent-outbox" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "52bc21c50fcc8f57155e5a2b4045b29716f6cc440d76d6f6e8f8360ae21c67ee"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.0/agent-outbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7302f264e8a3763849cf01150b6b2d77af38011637d73e1792d37e5285047a09"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.0/agent-outbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5e2f61d9e83866fd08f2efb34b994262a41a6546f9559486e6c3268281637ba"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.0/agent-outbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "762fff61e2f66c45fe2dd686501d4603e1075edfe4bdfc8c7d60b56526ef1de8"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.0/agent-outbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent-outbox"
  desc "Command-line client for agent-prepared work"
  homepage "https://agent-outbox.dev/"

  livecheck do
    skip "Generated for a numbered release."
  end

  binary "agent-outbox"
end
