# This file was generated by Agent Outbox. DO NOT EDIT.
cask "agent-outbox" do
  version "0.6.2"

  on_macos do
    on_arm do
      sha256 "2ff785bbe5ab8a0e46572fab8e7ab793c33953ba9964424864430a71b705b871"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.2/agent-outbox_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f600d8ec5e0b2bd8ca63e6211747515d6978edf4a5029aceae99ee6a76f464e"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.2/agent-outbox_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9deed9b91346704223f4ab29051370906f5bbf4c0b25fda5d573bc1de675b913"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.2/agent-outbox_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a95b3a640db62a024ae7e3be06b0393515d31589c71caef2ae232e17817cbb6e"
      url "https://github.com/conn-castle/agent-outbox/releases/download/v0.6.2/agent-outbox_#{version}_linux_amd64.tar.gz"
    end
  end

  name "agent-outbox"
  desc "Command-line client for agent-prepared work"
  homepage "https://agent-outbox.dev/"

  livecheck do
    skip "Generated for a numbered release."
  end

  binary "agent-outbox"
end
